server {
	listen		80;
	server_name nginx-lab.com;
	root		/var/www;
	index		index.html;
	autoindex	off;
	
	location /redir_1 {
		return 301 /permanent_redir;
	}
	
	location /redir_2 {
		return 302 /temporary_redir;
	}
	
	location /redir_3 {
		return 307 /temporary_redir;
	}
	
	location /redir_4 {
		return 308 /permanent_redir;
	}
	
	location /redir_0 {
		return 300 /redir;
	}
	
	location /restricted_methods {
	}
	
	location /autoindex {
	}
	
	location /index.html {
	}
	
	location /error_page {
	}
	
	location /subdir {
	}
}

